### PR TITLE
fixed type of SelectRate to be float

### PR DESCRIPTION
**Pull request by danoctavian**

### CODE REVIEW

**Comment by danoctavian** [comment]
it broke while i was running it on a set of matches, the serverside value was a float. it probably didn't break before because in most cases it's 0.

**Comment by d6o** [comment]
Nice! 
Thank you for your contribution @danoctavian !!! TinderGo still pretty beta, i will publish a more stable and complete version this weekend.

**Comment by danoctavian** [comment]
@DiSiqueira cool, looks good so far

**Comment by A4Andy89** [comment]
Hello, I wanted to ask about what the news is so far with being able to check tinder like this? 
I met this really amazing woman, however I'm getting a really bad feeling about everything.

**Pull request merged**
